"""empty message

Revision ID: 051ecd5a2bdc
Revises: 
Create Date: 2021-02-12 13:42:09.816534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.json import JSONType

# revision identifiers, used by Alembic.
revision = '051ecd5a2bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'flask_dance_oauth', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('token', JSONType(), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_dance_oauth')
    # ### end Alembic commands ###
